
const employee_info = [
    {
        eCode: 1,
        eName: "John Smith",
        Type: "Clerk",
        gradCode: 3,
        sectCode: 2,
        branchCode: 4,
        joiningDate: "2023-06-15",
        permDate: "2024-03-10",
        basic: 22000,
        ptDed: "Yes",
        corrAddress: "123 Main St, Cityville",
        permAddress: "456 Elm St, Townsville",
        FatherName: "Michael Smith",
        FAddress: "789 Oak St, Villageton",
        Caste: "General",
        Gender: "Male",
        bDay: "1990-05-20",
        IdentityMark: "Mole on left cheek",
        KnownLang: "English, Spanish",
        Education: "Bachelor's in Economics",
        BloodGrp: "O+",
        Mothertongue: "English"
    },
    {
        eCode: 2,
        eName: "Emily Johnson",
        Type: "Manager",
        gradCode: 5,
        sectCode: 1,
        branchCode: 3,
        joiningDate: "2022-09-20",
        permDate: "2023-12-05",
        basic: 35000,
        ptDed: "No",
        corrAddress: "789 Oak St, Villageton",
        permAddress: "123 Main St, Cityville",
        FatherName: "David Johnson",
        FAddress: "456 Elm St, Townsville",
        Caste: "General",
        Gender: "Female",
        bDay: "1985-11-10",
        IdentityMark: "Scar on right arm",
        KnownLang: "English, French",
        Education: "Master's in Business Administration",
        BloodGrp: "A-",
        Mothertongue: "English"
    },
    {
        eCode: 3,
        eName: "Michael Lee",
        Type: "Assistant Manager",
        gradCode: 4,
        sectCode: 3,
        branchCode: 2,
        joiningDate: "2023-02-12",
        permDate: "2023-11-25",
        basic: 30000,
        ptDed: "Yes",
        corrAddress: "456 Elm St, Townsville",
        permAddress: "789 Oak St, Villageton",
        FatherName: "James Lee",
        FAddress: "123 Main St, Cityville",
        Caste: "General",
        Gender: "Male",
        bDay: "1988-08-15",
        IdentityMark: "Tattoo on right forearm",
        KnownLang: "English, Chinese",
        Education: "Bachelor's in Finance",
        BloodGrp: "B+",
        Mothertongue: "English"
    },
    {
        eCode: 4,
        eName: "Sarah Williams",
        Type: "Clerk",
        gradCode: 2,
        sectCode: 4,
        branchCode: 1,
        joiningDate: "2024-01-05",
        permDate: "2024-09-15",
        basic: 25000,
        ptDed: "No",
        corrAddress: "234 Pine St, Hamletown",
        permAddress: "567 Cedar St, Villagetown",
        FatherName: "Christopher Williams",
        FAddress: "890 Maple St, Forestville",
        Caste: "General",
        Gender: "Female",
        bDay: "1992-04-30",
        IdentityMark: "Birthmark on neck",
        KnownLang: "English, German",
        Education: "Bachelor's in Accounting",
        BloodGrp: "AB-",
        Mothertongue: "English"
    },
    {
        eCode: 5,
        eName: "David Brown",
        Type: "Manager",
        gradCode: 5,
        sectCode: 5,
        branchCode: 5,
        joiningDate: "2023-07-18",
        permDate: "2024-04-20",
        basic: 38000,
        ptDed: "Yes",
        corrAddress: "567 Cedar St, Villagetown",
        permAddress: "234 Pine St, Hamletown",
        FatherName: "Richard Brown",
        FAddress: "890 Maple St, Forestville",
        Caste: "General",
        Gender: "Male",
        bDay: "1983-09-25",
        IdentityMark: "Scar above left eyebrow",
        KnownLang: "English, Italian",
        Education: "Master's in Business Administration",
        BloodGrp: "O+",
        Mothertongue: "English"
    },
    {
        eCode: 6,
        eName: "Jennifer Martinez",
        Type: "Clerk",
        gradCode: 3,
        sectCode: 2,
        branchCode: 4,
        joiningDate: "2022-11-30",
        permDate: "2023-10-05",
        basic: 24000,
        ptDed: "No",
        corrAddress: "890 Maple St, Forestville",
        permAddress: "345 Oak St, Villageton",
        FatherName: "Jose Martinez",
        FAddress: "678 Elm St, Townsville",
        Caste: "General",
        Gender: "Female",
        bDay: "1991-03-12",
        IdentityMark: "Mole on right arm",
        KnownLang: "English, Spanish",
        Education: "Bachelor's in Economics",
        BloodGrp: "A+",
        Mothertongue: "Spanish"
    },
    {
        eCode: 7,
        eName: "Daniel Taylor",
        Type: "Assistant Manager",
        gradCode: 4,
        sectCode: 3,
        branchCode: 2,
        joiningDate: "2023-04-08",
        permDate: "2024-01-15",
        basic: 31000,
        ptDed: "Yes",
        corrAddress: "678 Elm St, Townsville",
        permAddress: "890 Maple St, Forestville",
        FatherName: "William Taylor",
        FAddress: "345 Oak St, Villageton",
        Caste: "General",
        Gender: "Male",
        bDay: "1987-06-20",
        IdentityMark: "Tattoo on left wrist",
        KnownLang: "English, French",
        Education: "Bachelor's in Finance",
        BloodGrp: "B-",
        Mothertongue: "English"
    },
    {
        eCode: 8,
        eName: "Jessica Garcia",
        Type: "Manager",
        gradCode: 5,
        sectCode: 4,
        branchCode: 3,
        joiningDate: "2022-08-25",
        permDate: "2023-06-30",
        basic: 36000,
        ptDed: "No",
        corrAddress: "345 Oak St, Villageton",
        permAddress: "890 Maple St, Forestville",
        FatherName: "Carlos Garcia",
        FAddress: "678 Elm St, Townsville",
        Caste: "General",
        Gender: "Female",
        bDay: "1984-12-05",
        IdentityMark: "Scar on left cheek",
        KnownLang: "English, Spanish",
        Education: "Master's in Business Administration",
        BloodGrp: "AB+",
        Mothertongue: "Spanish"
    },
    {
        eCode: 9,
        eName: "Ryan Rodriguez",
        Type: "Clerk",
        gradCode: 2,
        sectCode: 1,
        branchCode: 5,
        joiningDate: "2023-01-10",
        permDate: "2023-09-20",
        basic: 23000,
        ptDed: "Yes",
        corrAddress: "456 Elm St, Townsville",
        permAddress: "789 Oak St, Villageton",
        FatherName: "Miguel Rodriguez",
        FAddress: "123 Main St, Cityville",
        Caste: "General",
        Gender: "Male",
        bDay: "1993-07-18",
        IdentityMark: "Birthmark on right arm",
        KnownLang: "English, Portuguese",
        Education: "Bachelor's in Accounting",
        BloodGrp: "O-",
        Mothertongue: "English"
    },
    {
        eCode: 10,
        eName: "Amanda Martinez",
        Type: "Assistant Manager",
        gradCode: 3,
        sectCode: 2,
        branchCode: 1,
        joiningDate: "2024-03-05",
        permDate: "2024-11-10",
        basic: 32000,
        ptDed: "On",
        corrAddress: "123 Main St, Cityville",
        permAddress: "456 Elm St, Townsville",
        FatherName: "Juan Martinez",
        FAddress: "789 Oak St, Villageton",
        Caste: "General",
        Gender: "Female",
        bDay: "1989-10-15",
        IdentityMark: "Scar on forehead",
        KnownLang: "English, Spanish",
        Education: "Bachelor's in Economics",
        BloodGrp: "A+",
        Mothertongue: "Spanish"
    }
];
module.exports = employee_info;